[server]
headless = true
#enableCORS = false

[theme]
# Primary accent color for interactive elements.
primaryColor = "#a3268c" 

# Background color for the main content area.
backgroundColor = "#631a56" #C64191" #00172B"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#a3268c"  # "#0083B8" #80d4ff

# Color used for almost all text.
textColor = "#ffffff"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
font = "sans serif"
